http:
  routers:
    # Identity Hub
    idhub-did:
      entrypoints:
        - web
        - websecure
      rule: PathPrefix(`/`) # && Host(`{{ env "DOMAIN" }}`) Host must not be set, because it will clash with the 'host' header. Should be fine in production
      service: idhub-did-svc
      tls:
    #        certresolver: edc-resolver
    idhub-identity:
      entrypoints:
        - web
        - websecure
      rule: Host(`{{ env "DOMAIN" }}`) && PathPrefix(`/api/identity`)
      service: idhub-identity-svc
      tls:
    #        certresolver: edc-resolver
    idhub-sts:
      entrypoints:
        - web
        - websecure
      rule: Host(`{{ env "DOMAIN" }}`) && PathPrefix(`/api/sts`)
      service: idhub-sts-svc
      tls:
    #        certresolver: edc-resolver
    idhub-credentials:
      entrypoints:
        - web
        - websecure
      rule: Host(`{{ env "DOMAIN" }}`) && PathPrefix(`/api/credentials`)
      service: idhub-credentials-svc
      tls:
    #        certresolver: edc-resolver

    # Control Plane
    ctrl-management:
      entrypoints:
        - web
        - websecure
      rule: Host(`{{ env "DOMAIN" }}`) && PathPrefix(`/management`)
      service: ctrl-management-svc
      tls:
    #        certresolver: edc-resolver
    ctrl-dsp:
      entrypoints:
        - web
        - websecure
      rule: Host(`{{ env "DOMAIN" }}`) && PathPrefix(`/dsp`)
      service: ctrl-dsp-svc
      tls:
    #        certresolver: edc-resolver

    # Data Plane
    data-public:
      entrypoints:
        - web
        - websecure
      rule: Host(`{{ env "DOMAIN" }}`) && PathPrefix(`/public`)
      service: data-public-svc
      tls:
    #        certresolver: edc-resolver

    flask-api:
      entrypoints:
        - web
        - websecure
      rule: Host(`{{ env "DOMAIN" }}`) && PathPrefix(`/flask`)
      service: flask-api-svc
      tls:
    #        certresolver: edc-resolver

  services:
    idhub-did-svc:
      loadBalancer:
        servers:
          - url: http://consumer-idhub
    idhub-identity-svc:
      loadBalancer:
        servers:
          - url: http://consumer-idhub:15151
    idhub-sts-svc:
      loadBalancer:
        servers:
          - url: http://consumer-idhub:9292
    idhub-credentials-svc:
      loadBalancer:
        servers:
          - url: http://consumer-idhub:13131
    ctrl-management-svc:
      loadBalancer:
        servers:
          - url: http://consumer-controlplane:9010
    ctrl-dsp-svc:
      loadBalancer:
        servers:
          - url: http://consumer-controlplane:9020
    data-public-svc:
      loadBalancer:
        servers:
          - url: http://consumer-dataplane:9600
    flask-api-svc:
      loadBalancer:
        servers:
          - url: http://flaskapi-flask-api:5000
